## NumPy

In [11]:
#run import first (#can put any name, but prefer np)
import numpy as np      

## 1. Creating arrays & attributes

## creating arrays

In [ ]:
#np.zeros()
#np.ones()
#np.arange()
#np.linspace()

In [9]:
#np.zeros() - an array filled with zeros
#2 rows,3columns
np.zeros((2,3)) #The outer brackets define the function call.
                #The inner brackets define the shape of the array as a tuple.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#np.ones() - an array filled with ones
#2 rows, 3 cols
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#np.arrange(start,stop,step) - array of evenly spaced values in a given range
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
#np.linspace(start,stop,num) - array of evenly spaced values of specified interval
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## array attribute

In [28]:
#ndarray.shape - dimension of the array
#ndarray.size - total num of elements
#ndarray.dtype - data type of the array

list=[1,2,3,]   #ndarray
x=np.array(list)

print(x.shape)
print(x.size)
print(x.dtype)

(3,)
3
int32


In [32]:
#Ex1:
list=[1,2,3]
x=np.array(list)
x

array([1, 2, 3])

In [13]:
x.shape

(3,)

In [14]:
x.size

3

In [16]:
x.dtype

dtype('int32')

In [34]:
#Ex2:
list=[1.5,2,3]
x=np.array(list)
x

array([1.5, 2. , 3. ])

In [36]:
list=[1,2]
print(np.array(list))

[1 2]


In [38]:
x.dtype        #float refer to number with decimal places

dtype('float64')

In [40]:
#Create 2D arrays-use from list of lists
#Ex1:
list2=[1,2,3],[4,5,6]       #has 2 rows, separated by comma
b=np.array(list2)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
print(b.shape)
print(b.size)
print(b.dtype)

(2, 3)
6
int32


In [27]:
#Ex2:
c=np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
c.shape

(3, 2)

In [46]:
#Create 3D array (2,2,3) (depth, row, column)
list3=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
d=np.array(list3)
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
print(d.shape)
print(d.size)
print(d.dtype)

(2, 2, 3)
12
int32


In [56]:
np.zeros(2)

array([0., 0.])

In [43]:
np.zeros(2).shape

(2,)

In [45]:
np.zeros((2,3))   #2d array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.zeros((2,2,3))   #3d array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.ones(3)

array([1., 1., 1.])

In [62]:
#Arrange function, we pass in a start, a stop and a step size
#returns evenly spaced
np.arange(0,10,1)     #output will follow the step size 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [66]:
#in space,returns a specific number of evenly spaced value
np.linspace(0,10,5)     #give 5 elements(according to step size) 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [68]:
np.linspace(0,10,20)     ##give 20 elements(according to step size) 

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [74]:
d1arr=np.linspace(0,10,6)
d2arr=d1arr.reshape(2,3)    #(2x3 matric)=6 steps size, need to follow the step size number
print(d1arr)     #original array
print(d2arr)     #reshape array

[ 0.  2.  4.  6.  8. 10.]
[[ 0.  2.  4.]
 [ 6.  8. 10.]]


In [15]:
d1arr=np.linspace(0,10,12)
d2arr=d1arr.reshape(2,2,3)    
print(d1arr)   #it will print the output w/o array text    
print(d2arr)   #it will print both output

[ 0.          0.90909091  1.81818182  2.72727273  3.63636364  4.54545455
  5.45454545  6.36363636  7.27272727  8.18181818  9.09090909 10.        ]
[[[ 0.          0.90909091  1.81818182]
  [ 2.72727273  3.63636364  4.54545455]]

 [[ 5.45454545  6.36363636  7.27272727]
  [ 8.18181818  9.09090909 10.        ]]]


In [17]:
d1arr=np.linspace(0,10,12)
d2arr=d1arr.reshape(2,2,3)    
d1arr  #it will not shows the output,
d2arr  #it will print this part only, if not key in print

array([[[ 0.        ,  0.90909091,  1.81818182],
        [ 2.72727273,  3.63636364,  4.54545455]],

       [[ 5.45454545,  6.36363636,  7.27272727],
        [ 8.18181818,  9.09090909, 10.        ]]])

## 2. Array Indexing

In [77]:
#1D array - one index
#2D array - array[row,column]
#3D array - array[depth,row,column]
#fancy index - pair row & column at the same time

In [79]:
arr_1D=np.array([10,20,30,40,50])
arr_1D[2]    #refer to second index

30

In [81]:
#2D array of 3x3
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[1,1]    

5

In [85]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[:,1]    #include all row, but retain only column 1

array([2, 5, 8])

In [87]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[0,1] 

2

In [89]:
#3d array 2x3x3
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
               [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
print(arr_3D)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [91]:
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
               [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
print(arr_3D[1,1,0])

13


In [93]:
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
               [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
print(arr_3D[:,0,1])

[ 2 11]


In [101]:
#fancy indexing
arr_1D=np.array([10,20,30,40,50])
print(arr_1D[2])
print(arr_1D[[2,3]])  

30
[30 40]


In [105]:
#2D array of 3x3
#fancy index-pair row & column at the same time
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2D)
rows=[0,2]
cols=[1,2]
arr_2D[rows,cols]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 9])

In [107]:
#2D array of 3x3
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
rows=[0,2]
cols=[1,2]
print(arr_2D[rows,:])
arr_2D[rows,cols]

[[1 2 3]
 [7 8 9]]


array([2, 9])

In [109]:
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
               [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
depth_ind=[0,1]
row_ind=[0,1]
col_ind=[1,2]
arr_3D[depth_ind,row_ind,col_ind]
#return 2 elements based on the combination of the corresponding indices

array([ 2, 15])

In [117]:
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
               [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
depth_ind=[0,1]
row_ind=[0,1]
col_ind=[1,2]
print(arr_3D[depth_ind,:,:])
arr_3D[depth_ind,row_ind,col_ind]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([ 2, 15])

In [111]:
arr=np.array([10,20,30,40,50])
#create a boolean indexing by applying a conditon
cond=arr>30
cond   #print the condition of each element

array([False, False, False,  True,  True])

In [113]:
arr=np.array([10,20,30,40,50])
#create a boolean indexing by applying a conditon
cond=arr>30
arr[cond]#select the element

array([40, 50])

In [115]:
#select element greater than 20 and less than 50
cond=(arr>20)&(arr<50)
cond

array([False, False,  True,  True, False])

In [117]:
arr=np.array([10,20,30,40,50])
cond=(arr>20)&(arr<50)
arr[cond]

array([30, 40])

In [119]:
arr=np.array([1,2,3,4,5])
cond=(arr>2) & (arr<5)
print(arr[cond])
print(cond)

[3 4]
[False False  True  True False]


In [121]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=arr_2D>5
arr_2D[x]

array([6, 7, 8, 9])

In [123]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[arr_2D>5]

array([6, 7, 8, 9])

In [125]:
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
               [[10,11,12],
                 [13,14,15],
                 [16,17,18]]]
               )
print(arr_3D[arr_3D>10])

[11 12 13 14 15 16 17 18]


In [132]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
#slice from index 2 to 6(exlusive)
arr[2:6]

array([2, 3, 4, 5])

## 3. Array Slicing

In [130]:
#Chapter 3;List - [ start : end ]
#using : operator
#general syntax for slicing - [start:stop:step size]
#multinasinonal slicing - array[start1:stop1:step1, start2:stop2:step2, ...]

In [132]:
#Example for 1D 
#[start:stop:step size]
arr=np.array([10,20,30,40,50])

#basic slicing
print(arr[1:4])    #index 1 until 3
#slice with step
print(arr[::2])    #every 2nd element-refer to index 0,2,4,...
#reverse slicing
print(arr[::-1])   #reverse order

[20 30 40]
[10 30 50]
[50 40 30 20 10]


In [87]:
#Example for 2D
#2D array [row,column] - [start:stop:step size] = [start:stop:step size,start:stop:step size]
arr_2D=np.array([[1,2,3],
                 [4,5,6,],
                 [7,8,9]])

#extract a sub-array
print(arr_2D[0:2,1:3])
#select all rows,specific columns
print(arr_2D[:,1])
#select specific rows,all columns
print(arr_2D[1,:])
#step slicing
print(arr_2D[::2,::2])

[[2 3]
 [5 6]]
[2 5 8]
[4 5 6]
[[1 3]
 [7 9]]


In [89]:
#Example for 3D
#3D array [depth,row,column] - [start:stop:step size] = [start:stop:step size,start:stop:step size,start:stop:step size]
arr_3D=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])

#slice 1st layer of the array
print(arr_3D[0,:,:])
#extract the last column across all layer and rows
print(arr_3D[:,:,2])

[[1 2 3]
 [4 5 6]]
[[ 3  6]
 [ 9 12]]


In [93]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
#slice from index 2 to 6(exlusive)
print(arr[2:6])
#slice from start to 5(exlusive)
print(arr[:5])
#slice from index 3(inclusive) to end
print(arr[3:])
#slice with step size 2
print(arr[0:9:2])
#slice the last 3 element
print(arr[-3:])
#slice the element only
print(arr[-3])

[2 3 4 5]
[0 1 2 3 4]
[3 4 5 6 7 8 9]
[0 2 4 6 8]
[7 8 9]
7


In [103]:
arr_2D=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

#slice the first two rows and first two column
print(arr_2D[:2,:2])
#slice the last two rows and last two column
print(arr_2D[-2:,-2:])   #or
print(arr_2D[1:3,1:3])

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]


In [105]:
arr_2D[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [119]:
arr_3D=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
               [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

#slice the last depth,row1 to 2 and last column
print(arr_3D[-1:,1:3,-1:])  #or
print(arr_3D[1:,1:,2:])
#slice first depth,all rows and column from index 1
print(arr_3D[0,:,1:])   #or
print(arr_3D[0,0:3,1:3])

[[[15]
  [18]]]
[[[15]
  [18]]]
[[2 3]
 [5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


## 4. Array manipulation

#np.reshape() - reshaping arrays

#np.concatenante() - joins arrays along an axis

#np.vstack() , np.hstack() - join arrays vertically(horizontally)

#np.split() - split aprt an array into multiple arrays along an axis

#np.vsplit() , np.hsplit() - split an array vertically(horizontally)

In [13]:
#np.reshape() - reshape array
arr=np.array([1,2,3,4,5,6])
x=arr.reshape(2,3)
print(x)

[[1 2 3]
 [4 5 6]]


#axis=0, concatenate along rows(vertically)

#axis=1, concatenant along columns(horizontally)

#axis=2, concatenate into deeper dimentsion (depth, row, column)

In [19]:
#np.concatenate() -join arrays along the axis (structure kena sama)
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6]])  #double bracket sebab nak match dgn structure arr1 to be contacenated along axis
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [141]:
#np.vstack(),np.hstack() - join array verticall,horizontally
arr4=np.array([1,2,3])
arr5=np.array([4,5,6])
arr6=np.vstack((arr4,arr5))
arr7=np.hstack((arr4,arr5))
print(arr6)
print(arr7)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [23]:
#np.split() - split an array into multiple array along an axis
arr=np.array([1,2,3,4,5,6])
#split into 3 array
x=np.split(arr,3)
print(x)

arr1=np.array([7,8,9,10,11,12])
#split into 3 array
y=np.split(arr1,3)
y

[array([1, 2]), array([3, 4]), array([5, 6])]


[array([7, 8]), array([ 9, 10]), array([11, 12])]

In [33]:
#np.vsplit(),np.split() - split an array verticall,horizontally
arr=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
#vertical split into 2 subarrays
arr1=np.vsplit(arr,3)
print(arr1)

#horizontal split into 3 subarrays
arr2=np.hsplit(arr,3)
print(arr2)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [35]:
#1D array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
#concatenate along the first axis
con_1D=np.concatenate((arr1,arr2))
print(con_1D)

[1 2 3 4 5 6]


In [43]:
#2D array
arr3=np.array([[1,2],
               [3,4]])
arr4=np.array([[5,6],
               [7,8]])
#concatenate along the column(first axis)
con_2D=np.concatenate((arr3,arr4),axis=1)
print(con_2D)

[[1 2 5 6]
 [3 4 7 8]]


In [186]:
#2D array
arr3=np.array([[1,2],
               [3,4]])
arr4=np.array([[5,6],
               [7,8]])
#concatenate along the row(axis 0)
con_2D_2=np.concatenate((arr3,arr4),axis=0)
print(con_2D_2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
#3D array
#generate numbers from 0 to 17 (has 18 numbers)
#reshape into 3D array(depth,row,column)
arr1=np.arange(18).reshape(2,3,3)

#generate numbers from 18 to 37 (has 18 numbers)
#reshape into 3D array(depth,row,column)
arr2=np.arange(18,36).reshape(2,3,3)
print(arr1)
print(arr2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]


In [27]:
arr1=np.arange(18).reshape(2,3,3)
arr2=np.arange(18,36).reshape(2,3,3)

#concatenate along axis 0
c_0=np.concatenate((arr1,arr2),axis=0)
print(c_0.shape)

#concatenate along axis 1 row
c_1=np.concatenate((arr1,arr2),axis=1)
print(c_1.shape)

#concatenate along axis 2 column
c_2=np.concatenate((arr1,arr2),axis=2)
print(c_2.shape)

(4, 3, 3)
(2, 6, 3)
(2, 3, 6)


In [212]:
#2D array
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6],[7,8]])
#concatenate along the row(axis 0)
con_2D_2=np.concatenate((arr3,arr4),axis=0)
print(con_2D_2)
print(np.hstack((arr3,arr4)))    #col-wise
print(np.vstack((arr3,arr4)))   #row-wise

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [222]:
arr=np.arange(10)
print(arr)

#split 2 equal parts
split_arr=np.split(arr,2)
print(split_arr)

#split based on indices
split_ind=np.split(arr,[3,7])   #split at index 3 & 7
print(split_ind)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


In [220]:
#np.split; split your array ubti multiple sub-arrays
arr=np.arange(10)
print(arr)

#split 2 equal parts
split_arr=np.split(arr,2)
print(split_arr)

#split based on indices
split_ind=np.split(arr,[3,7])   #split at index 3 & 7
print(split_ind)

#EX1: diff printing 
for part in split_ind:
    print(part)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]
[0 1 2]
[3 4 5 6]
[7 8 9]


In [224]:
#2D aray
arr=np.arange(24).reshape(6,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [228]:
arr=np.arange(24).reshape(6,4)
print(arr)

#split the array at specific indices along the rows
split_arr=np.split(arr,[2,4],axis=0)
print(split_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


In [230]:
arr=np.arange(24).reshape(6,4)
print(arr)

#split the array at specific indices along the column
split_arr1=np.split(arr,[1,2],axis=1)
print(split_arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]]), array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]


In [240]:
#3D array
arr=np.arange(12).reshape(2,3,2)

#split into 2 parts along the depth
split0=np.split(arr,2,axis=0)
print(split0)

#split into 3 parts along the rows
split1=np.split(arr,3,axis=1)
print(split1)

#split into 2 parts along the col
split2=np.split(arr,2,axis=2)
print(split2)

[array([[[0, 1],
        [2, 3],
        [4, 5]]]), array([[[ 6,  7],
        [ 8,  9],
        [10, 11]]])]
[array([[[0, 1]],

       [[6, 7]]]), array([[[2, 3]],

       [[8, 9]]]), array([[[ 4,  5]],

       [[10, 11]]])]
[array([[[ 0],
        [ 2],
        [ 4]],

       [[ 6],
        [ 8],
        [10]]]), array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]]])]


## 19/11/2024

In [1]:
#run import first
import numpy as np       #can put any name, but prefer np

In [13]:
#Create 3D array (4x2x3)
arr=np.arange(24).reshape(4,2,3)
print(arr)

#split along the depth(axis=0)
split_arr_depth=np.split(arr,[2,3],axis=0)
print(split_arr_depth)

#split along the column(axis=2)
split_arr_col=np.split(arr,[1,2],axis=2)
print(split_arr_col)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
[array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]]), array([[[12, 13, 14],
        [15, 16, 17]]]), array([[[18, 19, 20],
        [21, 22, 23]]])]
[array([[[ 0],
        [ 3]],

       [[ 6],
        [ 9]],

       [[12],
        [15]],

       [[18],
        [21]]]), array([[[ 1],
        [ 4]],

       [[ 7],
        [10]],

       [[13],
        [16]],

       [[19],
        [22]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]],

       [[14],
        [17]],

       [[20],
        [23]]])]


In [15]:
for part in split_arr_col:
    print(part.shape)    #recheck back

(4, 2, 1)
(4, 2, 1)
(4, 2, 1)


In [29]:
#Create a 2D array(4x4)

arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr_v=np.split(arr2,2)
print(arr_v)

arr_s=np.split(arr2,[2],axis=0)
print(arr_s)

arr_sh=np.split(arr2,[2],axis=1)
print(arr_sh)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


## Ufunc & arithmethic


In [41]:
#Unary ufunc
arr=np.array([1,4,9,16,25])
#np.sqrt() - compute square root
a=np.sqrt(arr)
print(a)
#np.exp() - compute exponential (e^x)
b=np.exp(arr)
print(b)
#np.max() - find max value
c=np.max(arr)
print(c)
#np.argmax() - find index of the max value - answer refer to 25(index4)
d=np.argmax(arr)
print(d)

[1. 2. 3. 4. 5.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
25
4


In [69]:
##Define 2 array
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

#addition
add_r=a+b
print(add_r)

#subtraction
sub_r=a-b
print(sub_r)

#multiplication
mult_r=a*b
print(mult_r)

#divide
div_r=a/b
print(div_r)

#power
pow_r=a**b
print(pow_r)

less_r=a<5
print(less_r)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ True  True  True  True]


In [49]:
#unary ufunc
arr=np.array([1,2,3,4,5])

np.mean(arr)  #try for med, sum, 

3.0

In [77]:
#binary ufunc - same result as line 43, but diff method
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
#addition
add_r=np.add(a,b)
print(add_r)
#subtraction
sub_r=np.subtract(a,b)
print(sub_r)
#multiplication
mult_r=np.multiply(a,b)
print(mult_r)
#divide
div_r=np.divide(a,b)
print(div_r)
#power
pow_r=np.power(a,b)
print(pow_r)
#less
less_r=np.less(a,4)
print(less_r)   

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ True  True  True False]


In [75]:
import time

#create a very large array
x=np.random.rand(1000000000)

start=time.time()
result_operator=x<5
print("Time using x<5:",time.time()-start)

Time using x<5: 0.9705290794372559


In [80]:
#matrix operation

A=np.array([[1,2],
            [3,4]])
B=np.array([[5,6],
            [7,8]])

mat_add=A+B
mat_mult=A@B
mat_tran=A.T

print(mat_add)
print(mat_mult)
print(mat_tran)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


## View & Copy

In [44]:
#original array
arr=np.array([1,2,3,4])
#create a view
view_arr=arr.view()
#modify the view - replace index 0 with 99
view_arr[0]=99
print(arr)
print(view_arr)

[99  2  3  4]
[99  2  3  4]


In [48]:
#original array
arr=np.array([1,2,3,4])
#create a copy
copy_arr=arr.copy()
#modify the copy
copy_arr[0]=99
print(arr)
print(copy_arr)

[1 2 3 4]
[99  2  3  4]


In [97]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

#slice the first two rows
view_arr=arr[0:2,:].copy()    #add copy here, to prevent the last step using modified array
print(view_arr)

#modify an element of view_arr
view_arr[0,0]=99     #replace first row,column with 99 values
print("Modified array with copy:")
print(view_arr)

print("\nOriginal array:")   #if previous statement not using copy, this part will print the modified array as original 
print(arr)

[[1 2 3]
 [4 5 6]]
Modified array with copy:
[[99  2  3]
 [ 4  5  6]]

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [99]:
#1st
arr=np.array([10,20,30,40])

#fancy index
fancy_view=arr[[1,3]]

#modify fancy_view
fancy_view[0]=99
print("Modified arr:",fancy_view)  #return to the original w/o specified the copy
print("Original arr:",arr)

Modified arr: [99 40]
Original arr: [10 20 30 40]


In [101]:
#2nd-same step but add copy statement only
arr=np.array([10,20,30,40])

#fancy index
fancy_view=arr[[1,3]].copy()    #just put copy to be save

#modify fancy_view
fancy_view[0]=99
print("Modified arr:",fancy_view)  #return to the original w/o specified the copy
print("Original arr:",arr)

Modified arr: [99 40]
Original arr: [10 20 30 40]


In [109]:
#Built a function to normalize the specific column in 2D array

def norm_col_2D(arr,col_index):
    norm_arr=arr.copy()
    col_arr=norm_arr[:,col_index]
    
    mean=np.mean(col_arr)
    std_dev=np.std(col_arr)
    
    norm_arr[:,col_index]=(col_arr-mean)/std_dev
    
    return norm_arr,arr

ori_arr=np.array([[60,70,80],
                 [90,100,110],
                 [120,130,140],
                 [150,160,170],
                 [180,190,200]])

modified_arr,original_arr=norm_col_2D(ori_arr,1)
print("Output:",modified_arr)
print("Input:",original_arr)

Output: [[ 60  -1  80]
 [ 90   0 110]
 [120   0 140]
 [150   0 170]
 [180   1 200]]
Input: [[ 60  70  80]
 [ 90 100 110]
 [120 130 140]
 [150 160 170]
 [180 190 200]]
